services:
  - type: web
    name: aitherfiles
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    disk:
      name: aitherfiles-storage
      mountPath: /data
      sizeGB: 3
    envVars:
      - key: AITHERFILES_STORAGE
        value: /data
